/* =========================================================================
   NGÂN HÀNG CÂU ĐỐ PHỤ — dùng cho ô THỬ THÁCH trên vòng quay
   -------------------------------------------------------------------------
   Mỗi dòng: ["Câu hỏi", ["đáp án ĐÚNG", "đáp án sai", "đáp án sai"]]

   ĐÁP ÁN ĐÚNG LUÔN ĐỨNG ĐẦU trong mảng. Trò chơi tự xáo trộn thứ tự khi hiện
   lên màn hình, nên bạn không cần tự đảo.

   Câu hỏi nên ngắn, trả lời được trong 15 giây.
   ========================================================================= */

(window.QUIZBANK = window.QUIZBANK || []).push(
["Một năm có bao nhiêu tháng có 31 ngày?", ["Bảy tháng", "Sáu tháng", "Năm tháng"]],
["Thủ đô của Nhật Bản là thành phố nào?", ["Tokyo", "Osaka", "Kyoto"]],
["Nước nào có diện tích lớn nhất thế giới?", ["Nga", "Canada", "Trung Quốc"]],
["Đại dương nào lớn nhất hành tinh?", ["Thái Bình Dương", "Đại Tây Dương", "Ấn Độ Dương"]],
["Kim loại nào ở thể lỏng trong điều kiện thường?", ["Thủy ngân", "Chì", "Nhôm"]],
["Loài vật nào ngủ đứng?", ["Ngựa", "Chó", "Mèo"]],
["Trái Đất quay quanh Mặt Trời hết bao lâu?", ["Khoảng 365 ngày", "Khoảng 30 ngày", "Khoảng 24 giờ"]],
["Bộ phận nào bơm máu đi khắp cơ thể?", ["Tim", "Phổi", "Gan"]],
["Chất khí nào cây xanh hút vào để quang hợp?", ["Cacbonic", "Oxi", "Nitơ"]],
["Việt Nam có bao nhiêu tỉnh thành giáp biển Đông?", ["Hai mươi tám", "Mười lăm", "Bốn mươi"]],
["Sông nào dài nhất Việt Nam?", ["Sông Đồng Nai", "Sông Hồng", "Sông Hương"]],
["Tỉnh nào là cực bắc của Việt Nam?", ["Hà Giang", "Lào Cai", "Cao Bằng"]],
["Ai là tác giả Truyện Kiều?", ["Nguyễn Du", "Nguyễn Trãi", "Hồ Xuân Hương"]],
["Thành phố nào được gọi là thành phố ngàn hoa?", ["Đà Lạt", "Sa Pa", "Huế"]],
["Một giờ có bao nhiêu giây?", ["Ba nghìn sáu trăm", "Sáu mươi", "Sáu trăm"]],
["Hình tam giác có tổng ba góc bằng bao nhiêu?", ["180 độ", "360 độ", "90 độ"]],
["Số nào là số nguyên tố?", ["Mười bảy", "Hai mươi mốt", "Mười lăm"]],
["Nửa của một phần tư là bao nhiêu?", ["Một phần tám", "Một phần hai", "Một phần sáu"]],
["Loài chim nào chạy nhanh nhất?", ["Đà điểu", "Chim cánh cụt", "Bồ câu"]],
["Loài vật nào có cổ dài nhất?", ["Hươu cao cổ", "Lạc đà", "Ngựa vằn"]],
["Con vật nào có thể sống không cần uống nước nhiều ngày?", ["Lạc đà", "Trâu", "Chó"]],
["Cá voi thuộc nhóm động vật nào?", ["Động vật có vú", "Loài cá", "Loài bò sát"]],
["Ong chúa trong tổ ong làm nhiệm vụ gì?", ["Đẻ trứng", "Lấy mật", "Canh cửa tổ"]],
["Loài nào là côn trùng?", ["Con bướm", "Con nhện", "Con giun"]],
["Nước sôi ở bao nhiêu độ C trong điều kiện thường?", ["100 độ", "50 độ", "150 độ"]],
["Nước đóng băng ở bao nhiêu độ C?", ["0 độ", "10 độ", "Âm 20 độ"]],
["Ánh sáng đi nhanh hơn hay âm thanh nhanh hơn?", ["Ánh sáng", "Âm thanh", "Bằng nhau"]],
["Vì sao ta thấy chớp trước khi nghe sấm?", ["Ánh sáng truyền nhanh hơn âm thanh", "Sấm xảy ra sau chớp", "Tai người phản ứng chậm"]],
["Hành tinh nào gần Mặt Trời nhất?", ["Sao Thủy", "Sao Kim", "Trái Đất"]],
["Mặt Trăng quay quanh thiên thể nào?", ["Trái Đất", "Mặt Trời", "Sao Hỏa"]],
["Người đầu tiên bay vào vũ trụ là ai?", ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin"]],
["Bộ phận nào của cây hút nước từ đất?", ["Rễ", "Lá", "Hoa"]],
["Loài cây nào lớn nhanh nhất thế giới?", ["Tre", "Thông", "Bàng"]],
["Quả nào có nhiều vitamin C nổi tiếng?", ["Cam", "Chuối", "Dưa hấu"]],
["Gạo được làm ra từ cây gì?", ["Cây lúa", "Cây ngô", "Cây khoai"]],
["Bánh chưng thường gói bằng lá gì?", ["Lá dong", "Lá chuối", "Lá sen"]],
["Nước mắm truyền thống làm từ nguyên liệu chính nào?", ["Cá cơm", "Đậu nành", "Tôm khô"]],
["Phở bò thường ăn kèm rau thơm nào?", ["Hành lá", "Rau muống", "Cải bắp"]],
["Tết Trung Thu diễn ra vào rằm tháng mấy âm lịch?", ["Tháng tám", "Tháng bảy", "Tháng chín"]],
["Áo dài Việt Nam thường xẻ tà ở đâu?", ["Hai bên hông", "Phía sau lưng", "Phía trước ngực"]],
["Nhạc cụ nào chỉ có một dây?", ["Đàn bầu", "Đàn tranh", "Đàn nhị"]],
["Múa rối nước biểu diễn ở đâu?", ["Trên mặt nước", "Trên sân khấu gỗ", "Trong hang động"]],
["Ai đánh tan quân Nam Hán trên sông Bạch Đằng năm 938?", ["Ngô Quyền", "Lê Lợi", "Trần Hưng Đạo"]],
["Hai Bà Trưng khởi nghĩa chống quân xâm lược nào?", ["Quân Hán", "Quân Minh", "Quân Nguyên"]],
["Kinh đô Thăng Long nay là thành phố nào?", ["Hà Nội", "Huế", "Ninh Bình"]],
["Vạn Lý Trường Thành nằm ở nước nào?", ["Trung Quốc", "Ấn Độ", "Mông Cổ"]],
["Tháp Eiffel nằm ở thành phố nào?", ["Paris", "Rome", "Madrid"]],
["Kim tự tháp nổi tiếng nằm ở nước nào?", ["Ai Cập", "Hy Lạp", "Peru"]],
["Nước nào có hình dạng giống chiếc ủng?", ["Ý", "Tây Ban Nha", "Hy Lạp"]],
["Đồng tiền của nước Nhật gọi là gì?", ["Yên", "Nhân dân tệ", "Won"]],
["Ngôn ngữ nào được nói nhiều nhất thế giới?", ["Tiếng Anh", "Tiếng Pháp", "Tiếng Đức"]],
["Từ tiếng Anh nào nghĩa là cảm ơn?", ["Thank you", "Sorry", "Please"]],
["Từ Monday trong tiếng Anh là thứ mấy?", ["Thứ hai", "Chủ nhật", "Thứ ba"]],
["Từ tiếng Anh nào nghĩa là quả táo?", ["Apple", "Orange", "Banana"]],
["Từ tiếng Anh nào nghĩa là bác sĩ?", ["Doctor", "Teacher", "Driver"]],
["Số twelve trong tiếng Anh là số mấy?", ["Mười hai", "Hai mươi", "Hai"]],
["Màu nào tạo ra khi trộn xanh dương và vàng?", ["Xanh lá", "Tím", "Cam"]],
["Màu nào tạo ra khi trộn đỏ và trắng?", ["Hồng", "Nâu", "Tím"]],
["Cầu vồng có bao nhiêu màu cơ bản?", ["Bảy", "Năm", "Chín"]],
["Bàn cờ vua có bao nhiêu ô?", ["Sáu mươi tư", "Bốn mươi chín", "Tám mươi mốt"]],
["Một đội bóng đá ra sân có bao nhiêu cầu thủ?", ["Mười một", "Chín", "Mười ba"]],
["Môn thể thao nào dùng quả cầu có lông vũ?", ["Cầu lông", "Tennis", "Bóng bàn"]],
["Cúp bóng đá thế giới tổ chức mấy năm một lần?", ["Bốn năm", "Hai năm", "Năm năm"]],
["Thế vận hội có biểu tượng mấy vòng tròn?", ["Năm", "Bốn", "Sáu"]],
["Môn nào thi đấu hoàn toàn dưới nước?", ["Bơi lội", "Điền kinh", "Đua xe đạp"]],
["Xe máy bắt buộc phải có gì khi tham gia giao thông?", ["Mũ bảo hiểm", "Còi to", "Gương ba chiều"]],
["Đèn giao thông màu vàng có nghĩa gì?", ["Chuẩn bị dừng", "Đi nhanh lên", "Rẽ phải"]],
["Bên nào ở Việt Nam xe chạy theo luật?", ["Bên phải", "Bên trái", "Tùy đường"]],
["Máy bay cất cánh và hạ cánh ở đâu?", ["Đường băng", "Bến cảng", "Ga tàu"]],
["Vật nào giúp định hướng bằng kim chỉ nam?", ["La bàn", "Đồng hồ", "Kính lúp"]],
["Thiết bị nào đo nhiệt độ cơ thể?", ["Nhiệt kế", "Cân", "Thước dây"]],
["Máy tính lưu dữ liệu tạm thời ở đâu?", ["Bộ nhớ RAM", "Màn hình", "Bàn phím"]],
["Chữ WWW trên internet viết tắt của gì?", ["World Wide Web", "World Web Working", "Wide World Wire"]],
["Email là cách gửi gì?", ["Thư điện tử", "Bưu phẩm", "Tiền"]],
["Mật khẩu mạnh nên có gì?", ["Chữ hoa chữ thường và số", "Toàn số 0", "Tên của mình"]],
["Pin điện thoại đo bằng đơn vị nào?", ["mAh", "Kilogram", "Mét"]],
["Ai được coi là cha đẻ của bóng đèn sợi đốt phổ biến?", ["Thomas Edison", "Isaac Newton", "Albert Einstein"]],
["Định luật vạn vật hấp dẫn gắn với tên ai?", ["Isaac Newton", "Galileo", "Nikola Tesla"]],
["Thuyết tương đối do ai xây dựng?", ["Albert Einstein", "Marie Curie", "Charles Darwin"]],
["Ai đưa ra thuyết tiến hóa?", ["Charles Darwin", "Louis Pasteur", "Gregor Mendel"]],
["Nhà khoa học nữ nào từng hai lần đoạt giải Nobel?", ["Marie Curie", "Ada Lovelace", "Rosalind Franklin"]],
["Cơ thể người có bao nhiêu chiếc răng khi trưởng thành đầy đủ?", ["Ba mươi hai", "Hai mươi", "Bốn mươi"]],
["Xương nào dài nhất cơ thể người?", ["Xương đùi", "Xương sống", "Xương cánh tay"]],
["Cơ quan nào lọc máu trong cơ thể?", ["Thận", "Dạ dày", "Phổi"]],
["Người lớn bình thường có bao nhiêu lít máu?", ["Khoảng 5 lít", "Khoảng 1 lít", "Khoảng 15 lít"]],
["Nên uống bao nhiêu nước mỗi ngày là hợp lý?", ["Khoảng 2 lít", "Khoảng 100 ml", "Khoảng 10 lít"]],
["Vitamin nào cơ thể tổng hợp được nhờ ánh nắng?", ["Vitamin D", "Vitamin C", "Vitamin B12"]],
["Loại thuốc nào không được tự ý dùng bừa bãi?", ["Kháng sinh", "Nước muối sinh lý", "Vitamin C"]],
["Hiện tượng Mặt Trăng che khuất Mặt Trời gọi là gì?", ["Nhật thực", "Nguyệt thực", "Sao băng"]],
["Sóng thần thường sinh ra sau hiện tượng nào?", ["Động đất ngoài khơi", "Mưa lớn", "Gió mùa"]],
["Bão ở Việt Nam thường đến vào mùa nào?", ["Mùa hè và mùa thu", "Mùa đông", "Mùa xuân"]],
["Khí nhà kính làm Trái Đất thế nào?", ["Nóng lên", "Lạnh đi", "Không đổi"]],
["Nguồn năng lượng nào là tái tạo?", ["Năng lượng mặt trời", "Than đá", "Dầu mỏ"]],
["Rác nào nên bỏ vào thùng tái chế?", ["Chai nhựa sạch", "Thức ăn thừa", "Pin cũ"]],
["Loài nào giúp thụ phấn cho hoa nhiều nhất?", ["Ong", "Kiến", "Gián"]],
["Rừng ngập mặn có vai trò gì với bờ biển?", ["Chắn sóng và giữ đất", "Làm nước mặn hơn", "Ngăn mưa"]],
["Con vật nào biến thái hoàn toàn từ nòng nọc?", ["Ếch", "Rắn", "Thằn lằn"]],
["Bướm phát triển từ giai đoạn nào?", ["Sâu bướm", "Trứng cá", "Nòng nọc"]],
["Loài nào đổi màu da theo môi trường?", ["Tắc kè hoa", "Chuột đồng", "Thỏ rừng"]],
["Con vật nào được mệnh danh chúa sơn lâm?", ["Hổ", "Sư tử", "Gấu"]],
["Động vật lớn nhất hành tinh hiện nay là gì?", ["Cá voi xanh", "Voi châu Phi", "Cá mập trắng"]],
["Trống đồng Đông Sơn là hiện vật của nền văn hóa nào?", ["Văn hóa Việt cổ", "Văn hóa Chăm", "Văn hóa Khmer"]],
["Chùa Một Cột được dựng trên mấy trụ đá?", ["Một trụ", "Hai trụ", "Bốn trụ"]],
["Vịnh Hạ Long thuộc tỉnh nào?", ["Quảng Ninh", "Hải Phòng", "Nam Định"]],
["Hang Sơn Đoòng nằm ở tỉnh nào?", ["Quảng Bình", "Quảng Trị", "Nghệ An"]],
["Đảo lớn nhất Việt Nam là đảo nào?", ["Phú Quốc", "Cát Bà", "Côn Đảo"]],
["Đỉnh núi cao nhất Việt Nam tên là gì?", ["Phan Xi Păng", "Bạch Mã", "Tản Viên"]],
["Cà phê Việt Nam trồng nhiều nhất ở vùng nào?", ["Tây Nguyên", "Đồng bằng sông Hồng", "Duyên hải Bắc Bộ"]],
["Vùng nào là vựa lúa lớn nhất nước ta?", ["Đồng bằng sông Cửu Long", "Tây Bắc", "Bắc Trung Bộ"]],
["Ngày Nhà giáo Việt Nam là ngày nào?", ["20 tháng 11", "8 tháng 3", "1 tháng 6"]],
["Ngày Quốc tế Thiếu nhi là ngày nào?", ["1 tháng 6", "20 tháng 10", "2 tháng 9"]],
["Một thập kỷ là bao nhiêu năm?", ["Mười năm", "Một trăm năm", "Năm năm"]],
["Một thế kỷ là bao nhiêu năm?", ["Một trăm năm", "Mười năm", "Một nghìn năm"]],
["Tháng hai năm nhuận có bao nhiêu ngày?", ["Hai mươi chín", "Hai mươi tám", "Ba mươi"]],
["Chữ số La Mã X là số mấy?", ["Mười", "Năm", "Một trăm"]],
["Một tá bằng bao nhiêu?", ["Mười hai", "Mười", "Hai mươi"]],
["Một ki lô gam bằng bao nhiêu gam?", ["Một nghìn gam", "Một trăm gam", "Mười gam"]],
["Một mét bằng bao nhiêu xăng ti mét?", ["Một trăm", "Mười", "Một nghìn"]],
["Hình nào có bốn cạnh bằng nhau và bốn góc vuông?", ["Hình vuông", "Hình thoi", "Hình chữ nhật"]],
["Số 0 là số chẵn hay số lẻ?", ["Số chẵn", "Số lẻ", "Không phải cả hai"]]
);
